name: Create Unity Package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: find ./ -name \*.meta >> metaList

      - run: mkdir a

      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'a/output.unitypackage'
          include-files: metaList
      - uses: quabug/create-upm-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upm_package_path: a/
          upm_tag_prefix: essential/v
